def demo():
    s = "Hello World 123"
    print("capitalize():", "hello".capitalize())
    print("casefold():", "HELLO".casefold())
    print("center():", "hi".center(10, '*'))
    print("count():", "banana".count('a'))
    print("encode():", "text\u00A9".encode('utf-8'))
    print("endswith():", "test.py".endswith('.py'))
    print("expandtabs():", "01\t02\t03".expandtabs(4))
    print("find():", "abracadabra".find('ra'))
    print("format():", "{} {}".format('Hello', 'World'))
    print("format_map():", "{name} is {age}".format_map({'name':'Alice','age':30}))
    print("index():", "hello".index('e'))
    print("isalnum():", "abc123".isalnum())
    print("isalpha():", "abc".isalpha())
    print("isascii():", "abc".isascii())
    print("isdecimal():", "123".isdecimal())
    print("isdigit():", "123".isdigit())
    print("isidentifier():", "var_name".isidentifier())
    print("islower():", "abc".islower())
    print("isnumeric():", "123".isnumeric())
    print("isprintable():", "abc".isprintable())
    print("isspace():", "   ".isspace())
    print("istitle():", "This Is Title".istitle())
    print("isupper():", "ABC".isupper())
    print("join():", "#".join(['a','b','c']))
    print("ljust():", "left".ljust(10, '.'))
    print("lower():", "ABC".lower())
    print("lstrip():", "   spaced".lstrip())
    t = str.maketrans('abc', '123')
    print("maketrans()+translate():", "a-b-c".translate(t))
    print("partition():", "name:age".partition(':'))
    print("replace():", "blue".replace('blue', 'red'))
    print("rfind():", "abracadabra".rfind('ra'))
    print("rindex():", "abracadabra".rindex('ra'))
    print("rjust():", "right".rjust(10, '.'))
    print("rpartition():", "a.b.c".rpartition('.'))
    print("rsplit():", "a,b,c,d".rsplit(',', 2))
    print("rstrip():", "trim   \n".rstrip())
    print("split():", "one two three".split())
    print("splitlines():", "line1\nline2\nline3".splitlines())
    print("startswith():", "hello.py".startswith('hello'))
    print("strip():", "   hello   ".strip())
    print("swapcase():", "AbC".swapcase())
    print("title():", "hello world".title())
    print("translate():", "abcxyz".translate(str.maketrans({'x':'X','y':'Y','z':'Z'})))
    print("upper():", s.upper())
    print("zfill():", "42".zfill(5))
    print(bool("Hello"))

    thislist = ["apple", "banana", "cherry"]
    print(len(thislist))
    
    #diff btw find() and index()
    print("find(not found):", "abc".find('z'))
    try:
        print("index(not found):", "abc".index('z'))
    except ValueError as e:
        print("index(not found) raised:", e)


if __name__ == '__main__':
    demo()
